#!/bin/bash
#SBATCH --job-name=ccwr-mine
#SBATCH --partition=gpu3080
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=6
#SBATCH --mem=32G
#SBATCH --time=12:00:00
#SBATCH --output=/storage/slurm/home/65070701701@cpe.kmutt.ac.th/contextual_cross_lingual_word_retrieval/output/%x_%j.out
#SBATCH --error=/storage/slurm/home/65070701701@cpe.kmutt.ac.th/contextual_cross_lingual_word_retrieval/output/%x_%j.err

echo "========== JOB INFO =========="
echo "Running on: $(hostname)"
echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"

echo "========== CHECK GPU =========="
nvidia-smi || echo "No GPU found!"

echo "========== LOAD ENV =========="
source ~/.bashrc
conda activate ccwr

python -c "import torch; print(torch.cuda.is_available())"
python -c "import torch; print(torch.cuda.get_device_name(0))"

echo "========== START GPU LOGGING =========="

GPU_LOG=/storage/slurm/home/65070701701@cpe.kmutt.ac.th/contextual_cross_lingual_word_retrieval/output/gpu_usage_${SLURM_JOB_ID}.log

while true; do
    echo "===== $(date) =====" >> $GPU_LOG
    nvidia-smi >> $GPU_LOG
    sleep 60
done &

GPU_MONITOR_PID=$!

echo "GPU monitor PID: $GPU_MONITOR_PID"

echo "========== RUN SCRIPT =========="

bash scripts/example_unsup_alignment_zh.sh

echo "========== STOP GPU LOGGING =========="
kill $GPU_MONITOR_PID

echo "========== DONE ==========to run for all 5 languages"
